# PLEASE READ THIS
# https://github.com/KSPActions/actions-docker-services/blob/main/README.md
# lets run searx for example.

name: docker-service
on: workflow_dispatch 

jobs:
  docker-service:
    runs-on: ubuntu-latest

    services:
      searx:
        image: searx/searx
        ports:
          - 8000:8080

    steps:
      - name: Install cloudflared
        run: |
          wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz
          mkdir -p cfd
          tar -xvzf cloudflared-stable-linux-amd64.tgz -C cfd
          chmod -R 777 cfd
          rm -rf cloudflared-stable-linux-amd64.tgz
      - name: tunnel cloudflared
        run: nohup ./cfd/cloudflared tunnel --no-autoupdate --logfile "/tmp/cloudflared.log" --url http://localhost:8000 > /dev/null 2>&1 &

      - name: show result link
        run: sleep 3s && grep -m 1 -oE "https://(.+)trycloudflare.com" /tmp/cloudflared.log

      - run: sleep 350m
